<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>

		<AssemblyTitle>Utility for discovering and uninstalling Windows Updates</AssemblyTitle>

		<ApplicationIcon>icon.ico</ApplicationIcon>
		<StartupObject>WinUpdateHelper.Program</StartupObject>
	</PropertyGroup>

	<ItemGroup>
	</ItemGroup>
</Project>