//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klocman.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Klocman.Properties.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        internal static string Enums_YesNoAsk_Ask {
            get {
                return ResourceManager.GetString("Enums_YesNoAsk_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name can&apos;t be empty..
        /// </summary>
        internal static string Error_SeparateArgsFromCommand_Empty {
            get {
                return ResourceManager.GetString("Error_SeparateArgsFromCommand_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending quotation mark is missing..
        /// </summary>
        internal static string Error_SeparateArgsFromCommand_MissingQuotationMark {
            get {
                return ResourceManager.GetString("Error_SeparateArgsFromCommand_MissingQuotationMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name must contain an extension separated by a dot..
        /// </summary>
        internal static string Error_SeparateArgsFromCommand_NoDot {
            get {
                return ResourceManager.GetString("Error_SeparateArgsFromCommand_NoDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string FileInfo_Attributes {
            get {
                return ResourceManager.GetString("FileInfo_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string FileInfo_Comments {
            get {
                return ResourceManager.GetString("FileInfo_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string FileInfo_CompanyName {
            get {
                return ResourceManager.GetString("FileInfo_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        internal static string FileInfo_CreationTime {
            get {
                return ResourceManager.GetString("FileInfo_CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string FileInfo_Directory {
            get {
                return ResourceManager.GetString("FileInfo_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists on drive.
        /// </summary>
        internal static string FileInfo_Exists {
            get {
                return ResourceManager.GetString("FileInfo_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string FileInfo_FileDescription {
            get {
                return ResourceManager.GetString("FileInfo_FileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string FileInfo_FileName {
            get {
                return ResourceManager.GetString("FileInfo_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Version.
        /// </summary>
        internal static string FileInfo_FileVersion {
            get {
                return ResourceManager.GetString("FileInfo_FileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FileInfo_FullName {
            get {
                return ResourceManager.GetString("FileInfo_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Name.
        /// </summary>
        internal static string FileInfo_InternalName {
            get {
                return ResourceManager.GetString("FileInfo_InternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is read only.
        /// </summary>
        internal static string FileInfo_IsReadOnly {
            get {
                return ResourceManager.GetString("FileInfo_IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string FileInfo_Language {
            get {
                return ResourceManager.GetString("FileInfo_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Access Time.
        /// </summary>
        internal static string FileInfo_LastAccessTime {
            get {
                return ResourceManager.GetString("FileInfo_LastAccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Write Time.
        /// </summary>
        internal static string FileInfo_LastWriteTime {
            get {
                return ResourceManager.GetString("FileInfo_LastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string FileInfo_LegalCopyright {
            get {
                return ResourceManager.GetString("FileInfo_LegalCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trademarks.
        /// </summary>
        internal static string FileInfo_LegalTrademarks {
            get {
                return ResourceManager.GetString("FileInfo_LegalTrademarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Filename.
        /// </summary>
        internal static string FileInfo_OriginalFilename {
            get {
                return ResourceManager.GetString("FileInfo_OriginalFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string FileInfo_ProductName {
            get {
                return ResourceManager.GetString("FileInfo_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Version.
        /// </summary>
        internal static string FileInfo_ProductVersion {
            get {
                return ResourceManager.GetString("FileInfo_ProductVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string FileInfo_Size {
            get {
                return ResourceManager.GetString("FileInfo_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigabytes.
        /// </summary>
        internal static string FileSize_GB_Long {
            get {
                return ResourceManager.GetString("FileSize_GB_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string FileSize_GB_Short {
            get {
                return ResourceManager.GetString("FileSize_GB_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilobytes.
        /// </summary>
        internal static string FileSize_KB_Long {
            get {
                return ResourceManager.GetString("FileSize_KB_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string FileSize_KB_Short {
            get {
                return ResourceManager.GetString("FileSize_KB_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabytes.
        /// </summary>
        internal static string FileSize_MB_Long {
            get {
                return ResourceManager.GetString("FileSize_MB_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string FileSize_MB_Short {
            get {
                return ResourceManager.GetString("FileSize_MB_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terabytes.
        /// </summary>
        internal static string FileSize_TB_Long {
            get {
                return ResourceManager.GetString("FileSize_TB_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string FileSize_TB_Short {
            get {
                return ResourceManager.GetString("FileSize_TB_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While this error does not require the application to shut down, some functionality might stop working. Most errors related to the filesystem can be safely ignored.
        ///
        ///Error message: {0}
        ///
        ///You can copy detailed information about this error to the clipboard by clicking the &quot;Copy&quot; button. Please consider sending this error information to the developer..
        /// </summary>
        internal static string PremadeDialogs_GenericError_Details {
            get {
                return ResourceManager.GetString("PremadeDialogs_GenericError_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has encountered an unexpected error.
        /// </summary>
        internal static string PremadeDialogs_GenericError_Heading {
            get {
                return ResourceManager.GetString("PremadeDialogs_GenericError_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner: .
        /// </summary>
        internal static string PremadeDialogs_GenericError_InnerExceptionTitle {
            get {
                return ResourceManager.GetString("PremadeDialogs_GenericError_InnerExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        internal static string PremadeDialogs_GenericError_Title {
            get {
                return ResourceManager.GetString("PremadeDialogs_GenericError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details:.
        /// </summary>
        internal static string PremadeDialogs_GenericErrorExtendedSafe_Heading {
            get {
                return ResourceManager.GetString("PremadeDialogs_GenericErrorExtendedSafe_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You might lose any unsaved data. To prevent data loss close the applications manually..
        /// </summary>
        internal static string PremadeDialogs_KillRunningProcessesQuestion_Details {
            get {
                return ResourceManager.GetString("PremadeDialogs_KillRunningProcessesQuestion_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to terminate all of the processes? .
        /// </summary>
        internal static string PremadeDialogs_KillRunningProcessesQuestion_Message {
            get {
                return ResourceManager.GetString("PremadeDialogs_KillRunningProcessesQuestion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate running processes.
        /// </summary>
        internal static string PremadeDialogs_KillRunningProcessesQuestion_Title {
            get {
                return ResourceManager.GetString("PremadeDialogs_KillRunningProcessesQuestion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path does not point to a valid .reg file.
        /// </summary>
        internal static string RegistryTools_AddRegToRegistry_FileNotExist {
            get {
                return ResourceManager.GetString("RegistryTools_AddRegToRegistry_FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot be empty or null.
        /// </summary>
        internal static string RegistryTools_RemoveRegistryKey_PathEmptyNull {
            get {
                return ResourceManager.GetString("RegistryTools_RemoveRegistryKey_PathEmptyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot point to a root key.
        /// </summary>
        internal static string RegistryTools_RemoveRegistryKey_PointsAtRoot {
            get {
                return ResourceManager.GetString("RegistryTools_RemoveRegistryKey_PointsAtRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove the default value.
        /// </summary>
        internal static string RegistryTools_RemoveRegistryKey_RemoveDefault {
            get {
                return ResourceManager.GetString("RegistryTools_RemoveRegistryKey_RemoveDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        internal static string ToFuzzyTimeSinceString_Days_Since {
            get {
                return ResourceManager.GetString("ToFuzzyTimeSinceString_Days_Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string ToFuzzyTimeSinceString_Days_Single {
            get {
                return ResourceManager.GetString("ToFuzzyTimeSinceString_Days_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        internal static string ToFuzzyTimeSinceString_Hours_Since {
            get {
                return ResourceManager.GetString("ToFuzzyTimeSinceString_Hours_Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One hour ago.
        /// </summary>
        internal static string ToFuzzyTimeSinceString_Hours_Single {
            get {
                return ResourceManager.GetString("ToFuzzyTimeSinceString_Hours_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        internal static string ToFuzzyTimeSinceString_JustNow {
            get {
                return ResourceManager.GetString("ToFuzzyTimeSinceString_JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        internal static string ToFuzzyTimeSinceString_Minutes_Since {
            get {
                return ResourceManager.GetString("ToFuzzyTimeSinceString_Minutes_Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One minute ago.
        /// </summary>
        internal static string ToFuzzyTimeSinceString_Minutes_Single {
            get {
                return ResourceManager.GetString("ToFuzzyTimeSinceString_Minutes_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        internal static string ToFuzzyTimeSinceString_Months_Since {
            get {
                return ResourceManager.GetString("ToFuzzyTimeSinceString_Months_Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One month ago.
        /// </summary>
        internal static string ToFuzzyTimeSinceString_Months_Single {
            get {
                return ResourceManager.GetString("ToFuzzyTimeSinceString_Months_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        internal static string ToFuzzyTimeSinceString_Years_Since {
            get {
                return ResourceManager.GetString("ToFuzzyTimeSinceString_Years_Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One year ago.
        /// </summary>
        internal static string ToFuzzyTimeSinceString_Years_Single {
            get {
                return ResourceManager.GetString("ToFuzzyTimeSinceString_Years_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
