//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UninstallTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UninstallTools.Properties.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webpage.
        /// </summary>
        internal static string AboutUrl {
            get {
                return ResourceManager.GetString("AboutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product code.
        /// </summary>
        internal static string BundleProviderKey {
            get {
                return ResourceManager.GetString("BundleProviderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall in Chocolatey.
        /// </summary>
        internal static string ChocolateyFactory_UninstallInChocolateyJunkName {
            get {
                return ResourceManager.GetString("ChocolateyFactory_UninstallInChocolateyJunkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All properties.
        /// </summary>
        internal static string ComparisonTargetInfo_AllProperties {
            get {
                return ResourceManager.GetString("ComparisonTargetInfo_AllProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        internal static string Confidence_Bad {
            get {
                return ResourceManager.GetString("Confidence_Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string Confidence_Good {
            get {
                return ResourceManager.GetString("Confidence_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty folder.
        /// </summary>
        internal static string Confidence_PF_EmptyFolder {
            get {
                return ResourceManager.GetString("Confidence_PF_EmptyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executables are present.
        /// </summary>
        internal static string Confidence_PF_ExecsPresent {
            get {
                return ResourceManager.GetString("Confidence_PF_ExecsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files are present.
        /// </summary>
        internal static string Confidence_PF_FilesPresent {
            get {
                return ResourceManager.GetString("Confidence_PF_FilesPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many files are present.
        /// </summary>
        internal static string Confidence_PF_ManyFilesPresent {
            get {
                return ResourceManager.GetString("Confidence_PF_ManyFilesPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program name is recognized.
        /// </summary>
        internal static string Confidence_PF_NameIsUsed {
            get {
                return ResourceManager.GetString("Confidence_PF_NameIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sub directories.
        /// </summary>
        internal static string Confidence_PF_NoSubdirs {
            get {
                return ResourceManager.GetString("Confidence_PF_NoSubdirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher is recognized.
        /// </summary>
        internal static string Confidence_PF_PublisherIsUsed {
            get {
                return ResourceManager.GetString("Confidence_PF_PublisherIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionable.
        /// </summary>
        internal static string Confidence_Questionable {
            get {
                return ResourceManager.GetString("Confidence_Questionable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry will be ran only once.
        /// </summary>
        internal static string Confidence_Startup_IsRunOnce {
            get {
                return ResourceManager.GetString("Confidence_Startup_IsRunOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry is matched to the application.
        /// </summary>
        internal static string Confidence_Startup_StartupMatched {
            get {
                return ResourceManager.GetString("Confidence_Startup_StartupMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Confidence_Unknown {
            get {
                return ResourceManager.GetString("Confidence_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very good.
        /// </summary>
        internal static string Confidence_VeryGood {
            get {
                return ResourceManager.GetString("Confidence_VeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is, or will be empty after removing junk..
        /// </summary>
        internal static string ConfidencePart_AllSubdirsMatched {
            get {
                return ResourceManager.GetString("ConfidencePart_AllSubdirsMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name did not match.
        /// </summary>
        internal static string ConfidencePart_CompanyNameDidNotMatch {
            get {
                return ResourceManager.GetString("ConfidencePart_CompanyNameDidNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name matched.
        /// </summary>
        internal static string ConfidencePart_CompanyNameMatch {
            get {
                return ResourceManager.GetString("ConfidencePart_CompanyNameMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is used by other installed applications.
        /// </summary>
        internal static string ConfidencePart_DirectoryStillUsed {
            get {
                return ResourceManager.GetString("ConfidencePart_DirectoryStillUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is explicitly mentioned in the uninstaller.
        /// </summary>
        internal static string ConfidencePart_ExplicitConnection {
            get {
                return ResourceManager.GetString("ConfidencePart_ExplicitConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removal of Store App data is problematic.
        /// </summary>
        internal static string ConfidencePart_IsStoreApp {
            get {
                return ResourceManager.GetString("ConfidencePart_IsStoreApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry entry of the uninstaller.
        /// </summary>
        internal static string ConfidencePart_IsUninstallerRegistryKey {
            get {
                return ResourceManager.GetString("ConfidencePart_IsUninstallerRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item seems to be a whole publisher category.
        /// </summary>
        internal static string ConfidencePart_ItemNameEqualsCompanyName {
            get {
                return ResourceManager.GetString("ConfidencePart_ItemNameEqualsCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name did not match very well.
        /// </summary>
        internal static string ConfidencePart_ProductNameDodgyMatch {
            get {
                return ResourceManager.GetString("ConfidencePart_ProductNameDodgyMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name matched perfectly.
        /// </summary>
        internal static string ConfidencePart_ProductNamePerfectMatch {
            get {
                return ResourceManager.GetString("ConfidencePart_ProductNamePerfectMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory name is questionable.
        /// </summary>
        internal static string ConfidencePart_QuestionableDirectoryName {
            get {
                return ResourceManager.GetString("ConfidencePart_QuestionableDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed icon.
        /// </summary>
        internal static string DisplayIcon {
            get {
                return ResourceManager.GetString("DisplayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimmed display name.
        /// </summary>
        internal static string DisplayNameTrimmed {
            get {
                return ResourceManager.GetString("DisplayNameTrimmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string DisplayVersion {
            get {
                return ResourceManager.GetString("DisplayVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path.
        /// </summary>
        internal static string Error_InvalidPath {
            get {
                return ResourceManager.GetString("Error_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or unknown startup registry key(s):.
        /// </summary>
        internal static string Error_InvalidRegKeys {
            get {
                return ResourceManager.GetString("Error_InvalidRegKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated size.
        /// </summary>
        internal static string EstimatedSize {
            get {
                return ResourceManager.GetString("EstimatedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains any.
        /// </summary>
        internal static string FilterComparisonMethod_Any {
            get {
                return ResourceManager.GetString("FilterComparisonMethod_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string FilterComparisonMethod_Contains {
            get {
                return ResourceManager.GetString("FilterComparisonMethod_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        internal static string FilterComparisonMethod_EndsWith {
            get {
                return ResourceManager.GetString("FilterComparisonMethod_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        internal static string FilterComparisonMethod_Equals {
            get {
                return ResourceManager.GetString("FilterComparisonMethod_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        internal static string FilterComparisonMethod_Regex {
            get {
                return ResourceManager.GetString("FilterComparisonMethod_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        internal static string FilterComparisonMethod_StartsWith {
            get {
                return ResourceManager.GetString("FilterComparisonMethod_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can start automatically.
        /// </summary>
        internal static string HasStartupEntries {
            get {
                return ResourceManager.GetString("HasStartupEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of installation.
        /// </summary>
        internal static string InstallDate {
            get {
                return ResourceManager.GetString("InstallDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation location.
        /// </summary>
        internal static string InstallLocation {
            get {
                return ResourceManager.GetString("InstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation source.
        /// </summary>
        internal static string InstallSource {
            get {
                return ResourceManager.GetString("InstallSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a 64bit application.
        /// </summary>
        internal static string Is64Bit {
            get {
                return ResourceManager.GetString("Is64Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is unregistered.
        /// </summary>
        internal static string IsOrphaned {
            get {
                return ResourceManager.GetString("IsOrphaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is protected.
        /// </summary>
        internal static string IsProtected {
            get {
                return ResourceManager.GetString("IsProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is registered.
        /// </summary>
        internal static string IsRegistered {
            get {
                return ResourceManager.GetString("IsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is an update.
        /// </summary>
        internal static string IsUpdate {
            get {
                return ResourceManager.GetString("IsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is valid.
        /// </summary>
        internal static string IsValid {
            get {
                return ResourceManager.GetString("IsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application compatibility.
        /// </summary>
        internal static string Junk_AppCompat_GroupName {
            get {
                return ResourceManager.GetString("Junk_AppCompat_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio policy config.
        /// </summary>
        internal static string Junk_AudioPolicy_GroupName {
            get {
                return ResourceManager.GetString("Junk_AudioPolicy_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSID classes.
        /// </summary>
        internal static string Junk_Clsid_GroupName {
            get {
                return ResourceManager.GetString("Junk_Clsid_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files and directories.
        /// </summary>
        internal static string Junk_Drive_GroupName {
            get {
                return ResourceManager.GetString("Junk_Drive_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Log logs.
        /// </summary>
        internal static string Junk_EventLog_GroupName {
            get {
                return ResourceManager.GetString("Junk_EventLog_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall rule.
        /// </summary>
        internal static string Junk_FirewallRule_GroupName {
            get {
                return ResourceManager.GetString("Junk_FirewallRule_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed folder list.
        /// </summary>
        internal static string Junk_InstalledFolders_GroupName {
            get {
                return ResourceManager.GetString("Junk_InstalledFolders_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Files orphan.
        /// </summary>
        internal static string Junk_ProgramFilesOrphans_GroupName {
            get {
                return ResourceManager.GetString("Junk_ProgramFilesOrphans_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing up....
        /// </summary>
        internal static string Junk_Progress_Finishing {
            get {
                return ResourceManager.GetString("Junk_Progress_Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up junk scanners....
        /// </summary>
        internal static string Junk_Progress_Startup {
            get {
                return ResourceManager.GetString("Junk_Progress_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        internal static string Junk_Registry_GroupName {
            get {
                return ResourceManager.GetString("Junk_Registry_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        internal static string Junk_Shortcut_GroupName {
            get {
                return ResourceManager.GetString("Junk_Shortcut_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        internal static string Junk_Startup_GroupName {
            get {
                return ResourceManager.GetString("Junk_Startup_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracing information.
        /// </summary>
        internal static string Junk_Tracing_GroupName {
            get {
                return ResourceManager.GetString("Junk_Tracing_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstaller reference.
        /// </summary>
        internal static string Junk_UninstallerKey_GroupName {
            get {
                return ResourceManager.GetString("Junk_UninstallerKey_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstaller location.
        /// </summary>
        internal static string Junk_UninstallerLocation_GroupName {
            get {
                return ResourceManager.GetString("Junk_UninstallerLocation_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User assist.
        /// </summary>
        internal static string Junk_UserAssist_GroupName {
            get {
                return ResourceManager.GetString("Junk_UserAssist_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Error Reporting reports.
        /// </summary>
        internal static string Junk_WerReports_GroupName {
            get {
                return ResourceManager.GetString("Junk_WerReports_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence.
        /// </summary>
        internal static string JunkRemover_Confidence {
            get {
                return ResourceManager.GetString("JunkRemover_Confidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall worker stopped prematurely.
        /// </summary>
        internal static string ManagerError_PrematureWorkerStop {
            get {
                return ResourceManager.GetString("ManagerError_PrematureWorkerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped by user.
        /// </summary>
        internal static string ManagerError_Skipped {
            get {
                return ResourceManager.GetString("ManagerError_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify path.
        /// </summary>
        internal static string ModifyPath {
            get {
                return ResourceManager.GetString("ModifyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent uninstaller.
        /// </summary>
        internal static string ParentKeyName {
            get {
                return ResourceManager.GetString("ParentKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning application stores....
        /// </summary>
        internal static string Progress_AppStores {
            get {
                return ResourceManager.GetString("Progress_AppStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for Chocolatey packages.
        /// </summary>
        internal static string Progress_AppStores_Chocolatey {
            get {
                return ResourceManager.GetString("Progress_AppStores_Chocolatey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for Steam Apps.
        /// </summary>
        internal static string Progress_AppStores_Steam {
            get {
                return ResourceManager.GetString("Progress_AppStores_Steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for application templates.
        /// </summary>
        internal static string Progress_AppStores_Templates {
            get {
                return ResourceManager.GetString("Progress_AppStores_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for Windows Features.
        /// </summary>
        internal static string Progress_AppStores_WinFeatures {
            get {
                return ResourceManager.GetString("Progress_AppStores_WinFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for Windows Store Apps.
        /// </summary>
        internal static string Progress_AppStores_WinStore {
            get {
                return ResourceManager.GetString("Progress_AppStores_WinStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for Windows Updates.
        /// </summary>
        internal static string Progress_AppStores_WinUpdates {
            get {
                return ResourceManager.GetString("Progress_AppStores_WinUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning drives for applications....
        /// </summary>
        internal static string Progress_DriveScan {
            get {
                return ResourceManager.GetString("Progress_DriveScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering directories.
        /// </summary>
        internal static string Progress_DriveScan_Gathering {
            get {
                return ResourceManager.GetString("Progress_DriveScan_Gathering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating missing uninstaller information....
        /// </summary>
        internal static string Progress_GatherUninstallerInfo {
            get {
                return ResourceManager.GetString("Progress_GatherUninstallerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating missing information....
        /// </summary>
        internal static string Progress_GeneratingInfo {
            get {
                return ResourceManager.GetString("Progress_GeneratingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging discovered applications....
        /// </summary>
        internal static string Progress_Merging {
            get {
                return ResourceManager.GetString("Progress_Merging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging applications from drives.
        /// </summary>
        internal static string Progress_Merging_Drives {
            get {
                return ResourceManager.GetString("Progress_Merging_Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging applications from stores.
        /// </summary>
        internal static string Progress_Merging_Stores {
            get {
                return ResourceManager.GetString("Progress_Merging_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning installed MSI products....
        /// </summary>
        internal static string Progress_MSI {
            get {
                return ResourceManager.GetString("Progress_MSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} application GUIDs.
        /// </summary>
        internal static string Progress_MSI_sub {
            get {
                return ResourceManager.GetString("Progress_MSI_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning registry for uninstallers....
        /// </summary>
        internal static string Progress_Registry {
            get {
                return ResourceManager.GetString("Progress_Registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering registry keys.
        /// </summary>
        internal static string Progress_Registry_Gathering {
            get {
                return ResourceManager.GetString("Progress_Registry_Gathering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0}.
        /// </summary>
        internal static string Progress_Registry_Processing {
            get {
                return ResourceManager.GetString("Progress_Registry_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for start-up entries.
        /// </summary>
        internal static string Progress_Startup {
            get {
                return ResourceManager.GetString("Progress_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher name.
        /// </summary>
        internal static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimmed publisher name.
        /// </summary>
        internal static string PublisherTrimmed {
            get {
                return ResourceManager.GetString("PublisherTrimmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet uninstall is possible.
        /// </summary>
        internal static string QuietUninstallPossible {
            get {
                return ResourceManager.GetString("QuietUninstallPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet uninstall string.
        /// </summary>
        internal static string QuietUninstallString {
            get {
                return ResourceManager.GetString("QuietUninstallString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key name.
        /// </summary>
        internal static string RegistryKeyName {
            get {
                return ResourceManager.GetString("RegistryKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry path.
        /// </summary>
        internal static string RegistryPath {
            get {
                return ResourceManager.GetString("RegistryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Helper Object.
        /// </summary>
        internal static string Startup_Shortname_BrowserHelper {
            get {
                return ResourceManager.GetString("Startup_Shortname_BrowserHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Startup_ShortName_Service {
            get {
                return ResourceManager.GetString("Startup_ShortName_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string Startup_ShortName_Task {
            get {
                return ResourceManager.GetString("Startup_ShortName_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup commands.
        /// </summary>
        internal static string StartupEntries {
            get {
                return ResourceManager.GetString("StartupEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable this entry, the following file was not found:.
        /// </summary>
        internal static string StartupManager_FailedEnable_FileNotFound {
            get {
                return ResourceManager.GetString("StartupManager_FailedEnable_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string StartupManager_Loading {
            get {
                return ResourceManager.GetString("StartupManager_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They will no longer be opened during boot. Make sure the selected items are not required before removing them..
        /// </summary>
        internal static string StartupManager_Message_Delete_Details {
            get {
                return ResourceManager.GetString("StartupManager_Message_Delete_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected programs from startup?.
        /// </summary>
        internal static string StartupManager_Message_Delete_Header {
            get {
                return ResourceManager.GetString("StartupManager_Message_Delete_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Manager.
        /// </summary>
        internal static string StartupManager_Message_Delete_Title {
            get {
                return ResourceManager.GetString("StartupManager_Message_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a system component.
        /// </summary>
        internal static string SystemComponent {
            get {
                return ResourceManager.GetString("SystemComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstaller file name.
        /// </summary>
        internal static string UninstallerFullFilename {
            get {
                return ResourceManager.GetString("UninstallerFullFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstaller type.
        /// </summary>
        internal static string UninstallerKind {
            get {
                return ResourceManager.GetString("UninstallerKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstaller location.
        /// </summary>
        internal static string UninstallerLocation {
            get {
                return ResourceManager.GetString("UninstallerLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no valid way of uninstalling this entry.
        /// </summary>
        internal static string UninstallError_Nowaytouninstall {
            get {
                return ResourceManager.GetString("UninstallError_Nowaytouninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstaller returned error code: .
        /// </summary>
        internal static string UninstallError_UninstallerReturnedCode {
            get {
                return ResourceManager.GetString("UninstallError_UninstallerReturnedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstaller timed out.
        /// </summary>
        internal static string UninstallError_UninstallerTimedOut {
            get {
                return ResourceManager.GetString("UninstallError_UninstallerTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolatey.
        /// </summary>
        internal static string UninstallerType_Chocolatey {
            get {
                return ResourceManager.GetString("UninstallerType_Chocolatey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inno Setup.
        /// </summary>
        internal static string UninstallerType_InnoSetup {
            get {
                return ResourceManager.GetString("UninstallerType_InnoSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallShield.
        /// </summary>
        internal static string UninstallerType_InstallShield {
            get {
                return ResourceManager.GetString("UninstallerType_InstallShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Installer.
        /// </summary>
        internal static string UninstallerType_Msiexec {
            get {
                return ResourceManager.GetString("UninstallerType_Msiexec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullsoft Scriptable Install System .
        /// </summary>
        internal static string UninstallerType_NSIS {
            get {
                return ResourceManager.GetString("UninstallerType_NSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDBInst.
        /// </summary>
        internal static string UninstallerType_SdbInst {
            get {
                return ResourceManager.GetString("UninstallerType_SdbInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Delete.
        /// </summary>
        internal static string UninstallerType_SimpleDelete {
            get {
                return ResourceManager.GetString("UninstallerType_SimpleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        internal static string UninstallerType_Steam {
            get {
                return ResourceManager.GetString("UninstallerType_Steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Store App.
        /// </summary>
        internal static string UninstallerType_StoreApp {
            get {
                return ResourceManager.GetString("UninstallerType_StoreApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UninstallerType_Unknown {
            get {
                return ResourceManager.GetString("UninstallerType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Feature.
        /// </summary>
        internal static string UninstallerType_WindowsFeature {
            get {
                return ResourceManager.GetString("UninstallerType_WindowsFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Update.
        /// </summary>
        internal static string UninstallerType_WindowsUpdate {
            get {
                return ResourceManager.GetString("UninstallerType_WindowsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid filter.
        /// </summary>
        internal static string UninstallListEditor_InvalidFilter {
            get {
                return ResourceManager.GetString("UninstallListEditor_InvalidFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New condition.
        /// </summary>
        internal static string UninstallListEditor_NewCondition {
            get {
                return ResourceManager.GetString("UninstallListEditor_NewCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New filter.
        /// </summary>
        internal static string UninstallListEditor_NewFilter {
            get {
                return ResourceManager.GetString("UninstallListEditor_NewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches.
        /// </summary>
        internal static string UninstallListEditor_NothingMatched {
            get {
                return ResourceManager.GetString("UninstallListEditor_NothingMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot contain newlines.
        /// </summary>
        internal static string UninstallListItem_NewLineInValue {
            get {
                return ResourceManager.GetString("UninstallListItem_NewLineInValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty.
        /// </summary>
        internal static string UninstallListItem_ValueEmpty {
            get {
                return ResourceManager.GetString("UninstallListItem_ValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall is possible.
        /// </summary>
        internal static string UninstallPossible {
            get {
                return ResourceManager.GetString("UninstallPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string UninstallStatus_Completed {
            get {
                return ResourceManager.GetString("UninstallStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string UninstallStatus_Failed {
            get {
                return ResourceManager.GetString("UninstallStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string UninstallStatus_Invalid {
            get {
                return ResourceManager.GetString("UninstallStatus_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string UninstallStatus_Paused {
            get {
                return ResourceManager.GetString("UninstallStatus_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected.
        /// </summary>
        internal static string UninstallStatus_Protected {
            get {
                return ResourceManager.GetString("UninstallStatus_Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string UninstallStatus_Skipped {
            get {
                return ResourceManager.GetString("UninstallStatus_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling.
        /// </summary>
        internal static string UninstallStatus_Uninstalling {
            get {
                return ResourceManager.GetString("UninstallStatus_Uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string UninstallStatus_Waiting {
            get {
                return ResourceManager.GetString("UninstallStatus_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall string.
        /// </summary>
        internal static string UninstallString {
            get {
                return ResourceManager.GetString("UninstallString", resourceCulture);
            }
        }
    }
}
