<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<AssemblyName>EBUninstaller-console</AssemblyName>
		<RootNamespace>BCU_console</RootNamespace>

		<Product>EBUninstaller Pro Console CLI</Product>
		<AssemblyTitle>EBUninstaller Pro Command Line Interface for Scripting and Automation</AssemblyTitle>
		
		<ApplicationIcon>..\BulkCrapUninstaller\Resources\logo.ico</ApplicationIcon>
		<StartupObject>BCU_console.Program</StartupObject>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\UninstallTools\UninstallTools.csproj" />
	</ItemGroup>
</Project>