//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UninstallerAutomatizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UninstallerAutomatizer.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No | Decline.
        /// </summary>
        internal static string Auto_BadButtons {
            get {
                return ResourceManager.GetString("Auto_BadButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel | Abort | Back.
        /// </summary>
        internal static string Auto_CancelButtons {
            get {
                return ResourceManager.GetString("Auto_CancelButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall | OK | Accept | Apply | Close | Yes.
        /// </summary>
        internal static string Auto_GoodButtons {
            get {
                return ResourceManager.GetString("Auto_GoodButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of arguments..
        /// </summary>
        internal static string Error_Invalid_number_of_arguments {
            get {
                return ResourceManager.GetString("Error_Invalid_number_of_arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path, or file doesn&apos;t exist: {0}.
        /// </summary>
        internal static string Error_InvalidPath {
            get {
                return ResourceManager.GetString("Error_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation of {0} uninstallers is not supported..
        /// </summary>
        internal static string Error_NotSupported {
            get {
                return ResourceManager.GetString("Error_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown uninstaller type: {0}.
        /// </summary>
        internal static string Error_UnknownUninstallerType {
            get {
                return ResourceManager.GetString("Error_UnknownUninstallerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached to &quot;{0}&quot;.
        /// </summary>
        internal static string Message_Automation_AppAttached {
            get {
                return ResourceManager.GetString("Message_Automation_AppAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking on the &quot;{0}&quot; button..
        /// </summary>
        internal static string Message_Automation_ClickingButton {
            get {
                return ResourceManager.GetString("Message_Automation_ClickingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic uninstallation failed..
        /// </summary>
        internal static string Message_Automation_Failed {
            get {
                return ResourceManager.GetString("Message_Automation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} radio buttons..
        /// </summary>
        internal static string Message_Automation_FoundButtons {
            get {
                return ResourceManager.GetString("Message_Automation_FoundButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop-up window closed..
        /// </summary>
        internal static string Message_Automation_PopupClosed {
            get {
                return ResourceManager.GetString("Message_Automation_PopupClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a pop-up window - &quot;{0}&quot;..
        /// </summary>
        internal static string Message_Automation_PopupFound {
            get {
                return ResourceManager.GetString("Message_Automation_PopupFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reoccuring popup window detected!.
        /// </summary>
        internal static string Message_Automation_PopupRecurringFound {
            get {
                return ResourceManager.GetString("Message_Automation_PopupRecurringFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process failed to start..
        /// </summary>
        internal static string Message_Automation_ProcessFailedToStart {
            get {
                return ResourceManager.GetString("Message_Automation_ProcessFailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting known-good radio button: {0}.
        /// </summary>
        internal static string Message_Automation_SelectingGoodButton {
            get {
                return ResourceManager.GetString("Message_Automation_SelectingGoodButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting not-blacklisted radio button: {0}.
        /// </summary>
        internal static string Message_Automation_SelectingNotBadButton {
            get {
                return ResourceManager.GetString("Message_Automation_SelectingNotBadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for NSIS uninstaller to extract....
        /// </summary>
        internal static string Message_Automation_WaitingForNsisExtraction {
            get {
                return ResourceManager.GetString("Message_Automation_WaitingForNsisExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window closed..
        /// </summary>
        internal static string Message_Automation_WindowClosed {
            get {
                return ResourceManager.GetString("Message_Automation_WindowClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found window &quot;{0}&quot;..
        /// </summary>
        internal static string Message_Automation_WindowFound {
            get {
                return ResourceManager.GetString("Message_Automation_WindowFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for windows....
        /// </summary>
        internal static string Message_Automation_WindowSearching {
            get {
                return ResourceManager.GetString("Message_Automation_WindowSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically uninstalling &quot;{0}&quot;.
        /// </summary>
        internal static string Message_Starting {
            get {
                return ResourceManager.GetString("Message_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation was successful!.
        /// </summary>
        internal static string Message_Success {
            get {
                return ResourceManager.GetString("Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic uninstallation failed. Reason: {0}.
        /// </summary>
        internal static string Message_UninstallFailed {
            get {
                return ResourceManager.GetString("Message_UninstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cancelled the operation.
        /// </summary>
        internal static string Message_UserCancelled {
            get {
                return ResourceManager.GetString("Message_UserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon stopped because of: .
        /// </summary>
        internal static string UninstallHandler_DaemonStoppedReason {
            get {
                return ResourceManager.GetString("UninstallHandler_DaemonStoppedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid number.
        /// </summary>
        internal static string UninstallHandler_InvalidProcessNumber {
            get {
                return ResourceManager.GetString("UninstallHandler_InvalidProcessNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting automatizer as a daemon/service..
        /// </summary>
        internal static string UninstallHandler_StartDaemon {
            get {
                return ResourceManager.GetString("UninstallHandler_StartDaemon", resourceCulture);
            }
        }
    }
}
