name: EBUninstaller Pro - Publish to WinGet

on:
  release:
    types: [released]

jobs:
  publish:
    name: Submit Package to WinGet
    runs-on: ubuntu-latest
    steps:
      - name: Extract Version
        id: get-version
        run: |
          # Find version from tag name and format to 4 components
          version=$(echo "${{ github.event.release.tag_name }}" | awk -F. '{printf "%d.%d.%d.%d\n", substr($1, 2), $2, $3, $4}')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: WinGet Releaser Action
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: EhabYT.EBUninstallerPro
          version: ${{ steps.get-version.outputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
