//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBug.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NBug.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occurred. Closing application..
        /// </summary>
        internal static string UI_Console_Full_Message {
            get {
                return ResourceManager.GetString("UI_Console_Full_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occurred. Closing application..
        /// </summary>
        internal static string UI_Console_Minimal_Message {
            get {
                return ResourceManager.GetString("UI_Console_Minimal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occurred. Closing application..
        /// </summary>
        internal static string UI_Console_Normal_Message {
            get {
                return ResourceManager.GetString("UI_Console_Normal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string UI_Dialog_Full_Exception_Tab {
            get {
                return ResourceManager.GetString("UI_Dialog_Full_Exception_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string UI_Dialog_Full_General_Tab {
            get {
                return ResourceManager.GetString("UI_Dialog_Full_General_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a brief description of how we can reproduce the error:.
        /// </summary>
        internal static string UI_Dialog_Full_How_to_Reproduce_the_Error_Notification {
            get {
                return ResourceManager.GetString("UI_Dialog_Full_How_to_Reproduce_the_Error_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has crashed and it will now be dismissed. If you click Quit, the application will close immediately. If you click Send and Quit, the application will close and a bug report will be send..
        /// </summary>
        internal static string UI_Dialog_Full_Message {
            get {
                return ResourceManager.GetString("UI_Dialog_Full_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quit.
        /// </summary>
        internal static string UI_Dialog_Full_Quit_Button {
            get {
                return ResourceManager.GetString("UI_Dialog_Full_Quit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Contents.
        /// </summary>
        internal static string UI_Dialog_Full_Report_Contents_Tab {
            get {
                return ResourceManager.GetString("UI_Dialog_Full_Report_Contents_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Send and Quit.
        /// </summary>
        internal static string UI_Dialog_Full_Send_and_Quit_Button {
            get {
                return ResourceManager.GetString("UI_Dialog_Full_Send_and_Quit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string UI_Dialog_Full_Title {
            get {
                return ResourceManager.GetString("UI_Dialog_Full_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has crashed and it will now be dismissed.
        ///A bug report has been sent to the developers. We apologize for the inconvenience..
        /// </summary>
        internal static string UI_Dialog_Minimal_Message {
            get {
                return ResourceManager.GetString("UI_Dialog_Minimal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string UI_Dialog_Minimal_Title {
            get {
                return ResourceManager.GetString("UI_Dialog_Minimal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Continue.
        /// </summary>
        internal static string UI_Dialog_Normal_Continue_Button {
            get {
                return ResourceManager.GetString("UI_Dialog_Normal_Continue_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click quit, the application will close immediately..
        /// </summary>
        internal static string UI_Dialog_Normal_Message {
            get {
                return ResourceManager.GetString("UI_Dialog_Normal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quit.
        /// </summary>
        internal static string UI_Dialog_Normal_Quit_Button {
            get {
                return ResourceManager.GetString("UI_Dialog_Normal_Quit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string UI_Dialog_Normal_Title {
            get {
                return ResourceManager.GetString("UI_Dialog_Normal_Title", resourceCulture);
            }
        }
    }
}
