name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get-version
        run: |
          # Find the version from tag name and pad to 4 components
          version=$(echo "${{ github.event.release.tag_name }}" | awk -F. '{printf "%d.%d.%d.%d\n", substr($1, 2), $2, $3, $4}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Klocman.BulkCrapUninstaller
          version: ${{ steps.get-version.outputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
